using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;

public class GameInput : MonoBehaviour
{
	public event EventHandler OnInteract; // this event is called when 'performed' is called
	public event EventHandler OnInteractAlternate;

	// In thi project,we use both old input system and new input system
	private PlayerInputActions playerInputActions; // autogenerated by Unity(that's new Input System)

	private void Awake()
	{
		playerInputActions = new PlayerInputActions();
		playerInputActions.Player.Enable(); // enable player movement form new input system

		playerInputActions.Player.Interact.performed += Interact_performed; // this event is called, when we press 'E'
		playerInputActions.Player.InteractAlternate.performed += InteractAlternate_performed;
	}

	private void InteractAlternate_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj)
	{
		OnInteractAlternate?.Invoke(this, EventArgs.Empty);
	}

	private void Interact_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj) // event, which is fired, when we press 'E'
	{
		OnInteract?.Invoke(this, EventArgs.Empty); // here we notify all listeners
	}

	public Vector2 GetVectorMovementNormalized()
    {
		Vector2 inputVector = playerInputActions.Player.Move.ReadValue<Vector2>(); // read WASD(Arrows, Joystick) values
		 
		inputVector = inputVector.normalized; // we make that vector normalized

		return inputVector;
    }
}
